<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="10.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.*">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="NSwag.AspNetCore" Version="14.7.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ahk.Web.Data\Ahk.Web.Data.csproj" />
    <ProjectReference Include="..\Ahk.Web.Services\Ahk.Web.Services.csproj" />
  </ItemGroup>

</Project>
