name: GitHub Monitor - build

on:
  push:
    paths:
      - "github-monitor/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "8.0.x"

      - name: "Run dotnet build"
        working-directory: github-monitor
        run: |
          dotnet build
          dotnet test
