name: GitHub Monitor - Azure publish

on: [workflow_dispatch]

# TODO avoid job steps copy paste with composite actions

jobs:
  publish_mobweb:
    environment: mobweb
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: "Run dotnet build"
        working-directory: github-monitor
        run: dotnet build --configuration Release --output ./output

      - name: "Run Azure Functions Action"
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ahk-github-monitor
          package: "./github-monitor/output"
          publish-profile: ${{ secrets.GITHUBMONITOR_AZUREPUBLISHPROFILE }}

  publish_adatvez:
    environment: adatvez
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: "Run dotnet build"
        working-directory: github-monitor
        run: dotnet build --configuration Release --output ./output

      - name: "Run Azure Functions Action"
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ahk-github-monitor
          package: "./github-monitor/output"
          publish-profile: ${{ secrets.GITHUBMONITOR_AZUREPUBLISHPROFILE }}
          
  publish_viauav21:
    environment: viauav21
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: "Run dotnet build"
        working-directory: github-monitor
        run: dotnet build --configuration Release --output ./output

      - name: "Run Azure Functions Action"
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ahk-github-monitor
          package: "./github-monitor/output"
          publish-profile: ${{ secrets.GITHUBMONITOR_AZUREPUBLISHPROFILE }}
          
  publish_viaubb03:
    environment: viaubb03
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: "Run dotnet build"
        working-directory: github-monitor
        run: dotnet build --configuration Release --output ./output

      - name: "Run Azure Functions Action"
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ahk-github-monitor
          package: "./github-monitor/output"
          publish-profile: ${{ secrets.GITHUBMONITOR_AZUREPUBLISHPROFILE }}

  publish_viauab01:
    environment: viauab01
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: "Run dotnet build"
        working-directory: github-monitor
        run: dotnet build --configuration Release --output ./output

      - name: "Run Azure Functions Action"
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ahk-github-monitor
          package: "./github-monitor/output"
          publish-profile: ${{ secrets.GITHUBMONITOR_AZUREPUBLISHPROFILE }}

  publish_viaumb02:
    environment: viaumb02
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: "Run dotnet build"
        working-directory: github-monitor
        run: dotnet build --configuration Release --output ./output

      - name: "Run Azure Functions Action"
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ahk-github-monitor
          package: "./github-monitor/output"
          publish-profile: ${{ secrets.GITHUBMONITOR_AZUREPUBLISHPROFILE }}
