name: Publish to GHCR

on: [workflow_dispatch]

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push to GitHub Container Registry
        working-directory: publish-results-pr
        run: |
          docker build -t ghcr.io/tanaiadam/publish-result:latest .
          docker push ghcr.io/tanaiadam/publish-result:latest
